language: csharp

os:
  - linux
#  - osx

mono:
  - latest
  - beta
  - alpha
  - nightly

sudo: false  # use the new container-based Travis infrastructure

script:
  - chmod u+x ./build.sh
  - ./build.sh All
