language: csharp

os:
  - linux
#  - osx

mono:
  - latest
  - nightly

matrix:
  allow_failures:
#    - os: osx
    - mono: nightly

sudo: false  # use the new container-based Travis infrastructure

script:
  - chmod u+x ./build.sh
  - ./build.sh All
